export const CATEGORIES = [
  'electronics',
  'vehicles',
  'property',
  'furniture',
  'clothing',
  'sports',
  'other',
] as const

export const LOCATIONS = [
  'Rīga',
  'Daugavpils',
  'Liepāja',
  'Jelgava',
  'Jūrmala',
  'Ventspils',
  'Rēzekne',
  'Valmiera',
  'Jēkabpils',
  'Ogre',
  'Tukums',
  'Salaspils',
  'Cēsis',
  'Kuldīga',
  'Olaine',
  'Saldus',
  'Talsi',
  'Dobele',
  'Bauska',
  'Sigulda',
  'Aizkraukle',
  'Alūksne',
  'Balvi',
  'Gulbene',
  'Krāslava',
  'Līvāni',
  'Ludza',
  'Madona',
  'Preiļi',
  'Limbaži',
  'Visa Latvija',
] as const

export type Category = typeof CATEGORIES[number]
export type Location = typeof LOCATIONS[number]
